name: ancestry_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - plink=1.90b6.21
  - bcftools=1.18
  - pandas=2.0
  - numpy=1.24
  - scipy=1.11
  - scikit-learn=1.3
  - matplotlib=3.7
  - seaborn=0.12
  - plotly=5.18
  - jinja2=3.1
  - tabulate=0.9
  - tqdm=4.65
  - wget
  - pip
  - pip:
    - kaleido  # for plotly static image export
